export const FetchPendingPostsApiUrl = "posts/pending"
export const ApprovePendingPostsApiUrl = "posts/approve"
export const DisapprovePendingPostsApiUrl = "posts/disapprove"
export const LoginApiUrl = "auth/login"
export const SignupApiUrl = "auth/signup"
export const FetchUserPostsUrl = "posts"
export const  DeletePostApiUrl ="posts/delete"
export const FetchNotificationsApiUrl ="notifications"
export const MarkNotificationAsReadUrl ="read"
export const FetchStoriesApiUrl = "posts/approved"
export const CreatePostUrl ="posts/create"
export const UpdatePostUrl = "posts/edit"
export const ForgotPasswordApiUrl = 'auth/forgot-password';
export const ResetPasswordApiUrl = 'auth/reset-password';
export const BackEndUrl = 'http://localhost:5000';
export const LogoutApiUrl = "auth/logout"